version: "3"

services:
  es-mysql:
    image: mysql:8
    hostname: es-mysql
    container_name: es-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    volumes:
      - ./db/initialisation/mysql.sql:/docker-entrypoint-initdb.d/initialisation.sql
    command:
      - --character-set-client-handshake=0
      - --sql_generate_invisible_primary_key=ON
  es-postgresql:
    image: postgres:13
    hostname: es-postgresql
    container_name: es-postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: es
    volumes:
      - ./db/initialisation/postgresql.sql:/docker-entrypoint-initdb.d/initialisation.sql
