version: "3"

services:
  account-db:
    image: mysql:8
    hostname: account-db
    container_name: account-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: welcome
    volumes:
      - ./api/db/initialisation:/docker-entrypoint-initdb.d
    command:
      - --character-set-client-handshake=0
      - --sql_generate_invisible_primary_key=ON
