on:
  pull_request:
    paths:
      - .github/workflows/account-ci.yaml
      - account/account
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

name: Account CI
run-name: Account CI by @${{ github.actor }}

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-account-${{ hashFiles('account/Cargo.lock') }}
      - name: Check
        run: |
          cd account
          cargo check
      - name: Format
        run: |
          cd account
          cargo fmt --check
      - name: Clippy
        run: |
          cd account
          cargo clippy -- --deny warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('account/Cargo.lock') }}
      - name: Build
        run: |
          cd account
          cargo build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('account/Cargo.lock') }}
      - name: Test
        run: |
          cd account
          cargo test
