on:
  pull_request:
    paths:
      - .github/workflows/event-sourcing-ci.yaml
      - event-sourcing/event-sourcing
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

name: EventSourcing CI
run-name: EventSourcing CI by @${{ github.actor }}

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-event-sourcing-${{ hashFiles('event-sourcing/Cargo.lock') }}
      - name: Check
        run: |
          cd event-sourcing
          cargo check
      - name: Format
        run: |
          cd event-sourcing
          cargo fmt --check
      - name: Clippy
        run: |
          cd event-sourcing
          cargo clippy -- --deny warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-event-sourcing-${{ hashFiles('event-sourcing/Cargo.lock') }}
      - name: Build
        run: |
          cd event-sourcing
          cargo build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            account/target/
          key: ${{ runner.os }}-cargo-event-sourcing-${{ hashFiles('event-sourcing/Cargo.lock') }}
      - name: Run Docker Compose
        run: |
          cd event-sourcing
          docker compose up -d
          sleep 10
      - name: Test
        run: |
          cd event-sourcing
          cargo test -- --include-ignored
